config/routes.rb
Frisbee::Application.routes.draw do
  devise_for :users

  resources :page do
    collection do
      get 'find_us'
      get 'about_us'
      get 'training'
    end
  end
  resources :articles do
    collection do
      get 'summarize'
    end
  end
  
  namespace 'admin' do
    resources :userpanel#, only: [:index, :show, :destroy, :edit, :update]
  end
  get 'gallery' => 'gallery#index', as: 'gallery'

  root :to => "home#index"
   get '/' => 'page#home', as: 'root'
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new
    

    if user.role? :admin
      can :manage, :all
    elsif user.role? :moderator
      can :manage, [ Article, Page]
    elsif user.role? :user
      can :read, [Article, Page]
      can :summarize, Article
      # can :read, [Article, Page]

      # manage products, assets he owns
      # can :manage, Comment do |comment|
      #   comment.try(:owner) == user
      # end
      # can :manage, Team do |team|
      #   team.try(:owner) == user
      # end
      
    else
      can :read, [Article, Page]
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, :content, presence: true
	belongs_to :user
	attr_accessible :content, :title, :user_id, :showOnHomepage


	def self.lastThree
		Article.where(showOnHomepage: true).order('created_at DESC').limit(3)
	end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :header, :name


  def getContent name
  	find_by_name(name)
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :users
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  has_and_belongs_to_many :roles
  validate :name, unique: true
  has_many :articles
  before_create :default_role

  def addRole role
    if role
      if role = Role.find_by_name(role)
        unless self.roles.include? role
          self.roles << role
          return 1
        end
        return 0 
      else
        return -1
      end
    end
  end

  def removeRole role
    if role
      if role = Role.find_by_name(role)
        if index = self.roles.index(role)
          self.roles.delete role
          return 1
        end
        return 0
      else
        return -1
      end
    end
  end


  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end

  private

  def default_role
    unless self.roles.first
      self.roles << Role.find_by_name('user')
    end
  end



end

app/controllers/admin/userpanel_controller.rb
class Admin::UserpanelController < ApplicationController
	load_and_authorize_resource :class => User

	def index
		# authorize! :show, User
		@users = User.all		
	end

	def destroy
		@user = User.find(params[:id])
		@user.delete

		redirect_to admin_userpanel_index_path
	end

	def edit
		
		@user = User.find(params[:id])
		@role_admin = @role_moderator = false
		@role_admin = true if  @user.roles.include? Role.find_by_name('admin') 
		@role_moderator = true if  @user.roles.include? Role.find_by_name('moderator') 
	end

	def update

		User.find(params[:id]).update_attributes(@user)
		@user = User.find(params[:id])
		@user.roles.delete_all

		@user.addRole(params[:admin])
		@user.addRole(params[:moderator])
		@user.addRole('user')

		# @user = User.find(params[:id])

		# render 'show'
		redirect_to admin_userpanel_index_path
		# redirect_to admin_userpanel_path(@user)
	end

	def show
		@user = User.find(params[:id])

		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
load_and_authorize_resource # initalizes all need members '@article(s)'

	def new
		@article = Article.new
	end

	def create
		@article = Article.create(params[:article])
		
		unless @article.save
			flash[:error] = " Article could not be saved"
			render 'new'
		else
			redirect_to articles_path
		end

	end

	def edit
	 	@article = Article.find(params[:id])
	end

	def update
		@article = params[:article]

		if Article.find(params[:id]).update_attributes(@article)
			redirect_to @article
		else
			flash[:error] = 'Article could not be saved'
			redirect_to edit_article_path @article
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def destroy
		@article = Article.find(params[:id])
		@article.delete

		redirect_to articles_path	
	end

	def index
		@articles = Article.order('created_at DESC')
		authorize! :read, Article
		# @articles = Article.all	
	end

	def summarize
		@articles = Article.all
	end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		# get the first 3 artivles
		@articles = Article::lastThree
	end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def index
		@pages = Page.all
	end

	def about_us
		@page = getContent('about us')
	end

	def find_us
		@page = getContent('find us')
	end

	def training
		@page = getContent('training')
	end

	def getContent(name)
		@page = Page.find_by_name(name)	
	end

	def show
		
	end

	def edit
		@page = Page.find(params[:id])	
	end

	def update
		@page = Page.find(params[:id])
		unless @page.update_attributes(params[:page])
			@page.error = 'Page could not be saved'
			redirect_to edit_page_path(@page)
		else
			render 'show'	
		end
	end

	def destroy
		
	end

	def create	
	end
end

app/helpers/admin/userpanel_helper.rb
module Admin::UserpanelHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def nav_active_link_helper(link_name, path, options = nil )
		html = ''
		# args[:controller] = controller
		# args[:action] = action
		# 
		if options && current_page?(options)
			html += "<li class='active'>"
		else
			html += "<li>"
		end
		html += link_to(link_name, path)
		html.html_safe
	end

	def print_params
		html = "<div id='params'>"
		params.each do |param|
			html += "<p> " + param.inspect + "</p>"
		end
		html += "</div>"
		html.html_safe

	end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/admin/userpanel/edit.html.erb
<h2>Edit <%= @user.name %></h2>

<%= form_for(@user, :url => admin_userpanel_path, :html => { :method => :put }) do |f| %>

  <div><%= f.label :name %><br />
  <%= f.email_field :name %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>


  <div>
  	<%= label_tag 'admin' %>
	<%= check_box_tag 'admin', 'admin',  checked = @role_admin %> <br>
	<%= label_tag 'moderator' %>
	<%= check_box_tag 'moderator','moderator' , checked = @role_moderator%>
   <br>
  <br>

  <div><%= f.submit "update" %></div>
<% end %>
<p><%= button_to "Delete account", admin_userpanel_path(@user), :data => { :confirm => "Are you sure?" }, :method => :delete %></p>

<%= link_to "Back", :back %>

app/views/admin/userpanel/index.html.erb
<h2>User Listing</h2>
<%= print_params %>
<table style='border: none'>
	<tr style ='text-align: border: none'>
		<th>ID</th>
		<th>Name</th>
		<th>Email</th>
		<th>Role</th>
		<th></th>
		<th></th>
	</tr>
	<% @users.each do |user| %>
	<tr>
		<td><%= user.id %></td>
		<td><%= user.name %></td>
		<td><%= user.email %></td>
		<td><% user.roles.map do |role| %>
			<%= role.name %>
			<% end %>
		</td>
		<td><%= link_to 'edit', edit_admin_userpanel_path(user) %></td>
		<td><%= link_to 'delete', admin_userpanel_path(user), method: 'delete' , confirm: 'are you sure? ' %></td>
	</tr>
	<% end %>
</table>

app/views/admin/userpanel/show.html.erb
<%= print_params %>
<table>
	<tr>
		<td>Name</td>
		<td><%= @user.name %></td>
	</tr>
	<tr>
		<td>Email</td>
		<td><%= @user.email %></td>
	</tr>
	<tr>
		<td>Roles</td>
		<td><% @user.roles.map do |role| %>
				<%= role.name %>
			<% end %>
		</td>
	</tr>
	<tr>
		<td></td>
		<td></td>
	</tr>
</table>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<%= f.label :title %> <br>
	<%= f.text_field :title, style: 'width: 300px' %><br>
	<br>
	<%= f.label :content %> <br>
	<%= f.text_area :content %> <br>
	<br>
	<%= f.submit 'submit' %>
<% end %>

app/views/articles/edit.html.erb
	<div class="box">
<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<% if can? :manage,  Article %> <%= link_to 'new', new_article_path %> <% end %>
<% @articles.each do |article| %>	

<div class="box">
	<% if can? :manage,  Article %> 
		<%= link_to 'edit', edit_article_path(article) %> <%= link_to 'delete' , article_path(article) , method: 'delete' %> 
		<div style='float: right'><%= 'homepage: ' +  article.showOnHomepage?.to_s %></div>
	<% end %>
	<p><%= article.title.html_safe %></p>
	<p><%= article.content.html_safe %></p>
</div>
<div class="clear"></div>
<br>
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
	<div class="box">

		<% if can? :update, Article %>
		<%= link_to 'edit' ,edit_article_path %>
		<% end %>
		
		<p class="tagline"><strong><%= @article.title %></strong></p> <br>
		<div class="content"><%= @article.content.html_safe %></div>
		<div class="clear"></div>
	</div>

app/views/articles/summarize.html.erb
<%= link_to 'new', new_article_path %>
<% @articles.each do |article| %>	

<div class="box">
<%= link_to 'edit', edit_article_path(article) %> <%= link_to 'delete' , article_path(article) , method: 'delete' %>
<p><%= article.title %></p>
<p><%= article.content %></p>
</div>
<div class="clear"></div>
<br>
<% end %>

app/views/gallery/index.html.erb
<% content_for :content do %>
<div class="container1">
  <h1>Headline: Gallery Page</h1>
  <div id="gallery" class="box">
    <ul>
      <li><%= link_to((image_tag 'template/featured1.jpg', width:260, height:190), image_path('template/slide1.jpg'), data: { :'gal'=> 'prettyPhoto[gallery2]'})%></li>
      <li><%= link_to(( image_tag 'template/featured2.jpg', width:260, height:190 ), image_path('template/slide2.jpg'), data: { :'gal'=> 'prettyPhoto[gallery2]'})%></li>
      <li class="last"><%= link_to(( image_tag 'template/featured3.jpg', width:260, height:190 ),
        image_path('template/slide3.jpg'), data: { :'gal'=> 'prettyPhoto[gallery2]'})%></li>
      <li><%= link_to(( image_tag 'template/featured1.jpg', width:260, height:190 ), image_path('template/slide1.jpg'), data: { :'gal'=> 'prettyPhoto[gallery2]'})%></li>
      <li><%= link_to(( image_tag 'template/featured2.jpg', width:260, height:190 ), image_path('template/slide2.jpg'), data: { :'gal'=> 'prettyPhoto[gallery2]'})%></li>
      <li class="last"><%= link_to(( image_tag 'template/featured3.jpg', width:260, height:190 ), image_path('template/slide3.jpg'), data: { :'gal'=>'prettyPhoto[gallery2]'})%></li>
      <li><%= link_to(( image_tag 'template/featured1.jpg', width:260, height:190 ), image_path('template/slide1.jpg'), data: { :'gal'=>'prettyPhoto[gallery2]'})%></li>
      <li><%= link_to(( image_tag 'template/featured2.jpg', width:260, height:190 ), image_path('template/slide2.jpg'), data: { :'gal'=> 'prettyPhoto[gallery2]'})%></li>
      <li class="last"><%= link_to(( image_tag 'template/featured3.jpg', width:260, height:190 ), image_path('template/slide3.jpg'), data: { :'gal'=> 'prettyPhoto[gallery2]'})%></li>
    </ul>
    <br class="clear" />
  </div>

  <br />

  <div class="clear"></div>
</div>


  <% end %>

app/views/layouts/_signup.html.erb
<span style="font-size:0.5em; margin-left:10px">
<% if user_signed_in? %>

	(<%= current_user.name %>) <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
	<%= link_to('edit', edit_user_registration_path) %>
<% else %>
	<%= link_to('Login', new_user_session_path) + " - " %> 
	<%= link_to('Sign up', new_user_registration_path)  %>

<% end %>
</span>

app/views/layouts/admin/userpanel.html.erb
<%= content_for :content do %>

<div class="container1">
<div class="box">
<%= yield %>
</div>
</div>

<% end %>

 <%= render template: 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Rosario Ultimate - Homepage</title>
<meta charset="utf-8" />
<%= stylesheet_link_tag "application", :media => "screen" %> 
<%= javascript_include_tag "elegant-press" %> 
<%= javascript_include_tag'application' %> 
<%= csrf_meta_tags %>
<!--[if IE]><style>#header h1 a:hover{font-size:75px;}</style><![endif]-->
</head>
<body>
  <div class="main-container">
    <header>
      <h1>
        <a href="/">Rosario Ultimate</a>
      </h1>
      <p id="tagline">
        <strong>the art of frisbee :)</strong>
      </p>
    </header>
  </div>
  <div class="main-container">
    <div id="sub-headline">
      <div class="tagline_left">
        <p id="tagline2">
          Mail: <a href="mailto:info@rosario-ultimate.com.ar">info@rosario-ultimate.com.ar</a>
          <%= render partial: 'layouts/signup' %>
        </p>
      </div>

      <div class="tagline_right">
        <form action="/" method="post">
          <fieldset>
            <legend>Site Search</legend>
            <input type="text" placeholder="Search Our Website&hellip;"
              onfocus="if (this.value == 'Search Our Website&hellip;') {this.value = '';}"
              onblur="if (this.value == '') {this.value = 'Search Our Website&hellip;';}" />
            <input type="submit" name="go" id="go" value="Search" />
          </fieldset>
        </form>
      </div>
      <br class="clear" />
    </div>
  </div>
  <div class="main-container">
    <div id="nav-container">
      <nav>
        <ul class="nav">
          <%= nav_active_link_helper('home', root_path,{ controller: '/home'}) %></li> 
          <%= nav_active_link_helper('about us', about_us_page_index_path,{ action: 'about_us', controller: '/page'}) %></li>
          <%= nav_active_link_helper('frisbee','/') %>
            <ul>
              <li><%= link_to 'Ultimate', '/' %>
              <ul>
                <li><a href='/'>Shots</a>
                  <ul>
                    <li><a href='/'>Backhand</a></li>
                    <li><a href='/'>Forehand</a></li>
                    <li><a href='/'>Hammer</a></li>
                    <li><a href='/'>Scoober</a></li>
                    <li><a href='/'>Thumber</a></li>
                  </ul>

                </li>
                <li><%= link_to 'rules', '/' %></li>
              </ul>
              </li>
              <li><%= link_to 'freestyle', '/' %></li>
            </ul>
          </li>
          <%= nav_active_link_helper('find us', find_us_page_index_path,{ action: 'find_us', controller: '/page'}) %></li>
          <%= nav_active_link_helper('training', training_page_index_path,{ action: 'training', controller: '/page'}) %></li>
          <%= nav_active_link_helper('gallery', gallery_path, {controller: '/gallery'}) %></li>
          <%= nav_active_link_helper('Tournament', '/') %></li>
          <li class="last"><%= link_to 'Blog', '/' %></li>
        </ul>
      </nav>
      <div class="clear"></div>
    </div>
  </div>
  <div class="flash" style='margin-left: 50%'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <div class="main-container"><%= content_for?(:content) ? yield(:content) : yield %>
  </div>
  <div class="main-container"></div>

<div class="callout">
  <div class="calloutcontainer">
    <div class="container_12">
      <div class="grid">
        <article class="footbox">
          <h2>From The Blog</h2>
          <ul>
            <li><a href="#">Lorem Ipsum Dolor</a><br /> Orciint erdum
              condimen terdum nulla mcorper elit nam curabitur...</li>
            <li><a href="#">Praesent Et Eros</a><br /> Orciint erdum
              condimen terdum nulla mcorper elit nam curabitur...</li>
            <li><a href="#">Suspendisse In Neque</a><br /> Orciint erdum
              condimen terdum nulla mcorper elit nam curabitur...</li>
          </ul>
        </article>
        <article class="footbox last">
          <h2>We Are Social!</h2>
          <div id="social">
            <a href="http://twitter.com/priteshgupta" class="s3d twitter">
              Twitter <span class="icons twitter"></span>
            </a> <a href="http://www.facebook.com/priteshgupta"
              class="s3d facebook"> Facebook <span class="icons facebook"></span>
            </a> <a href="http://forrst.com/people/priteshgupta"
              class="s3d forrst"> Forrst <span class="icons forrst"></span>
            </a> <a href="http://www.flickr.com/photos/priteshgupta"
              class="s3d flickr"> Flickr <span class="icons flickr"></span>
            </a> <a href="#" class="s3d designmoo"> Designmoo <span
              class="icons designmoo"></span>
            </a>
          </div>
        </article>
        <article class="latestgallery">
          <h2>Latest Work</h2>
          <ul>
            <li><a href="template/thumb.jpg"
              data-gal="prettyPhoto[gallery]" title="Title"><%= image_tag 'template/thumb.jpg', width: 150, height: 95 %></a></li>
            <li><a href="template/thumb2.jpg"
              data-gal="prettyPhoto[gallery]" title="Title"><%= image_tag 'template/thumb2.jpg', width: 150, height: 95 %></a></li>
            <li><a href="template/thumb3.jpg"
              data-gal="prettyPhoto[gallery]" title="Title"><%= image_tag 'template/thumb3.jpg', width: 150, height: 95 %></a></li>
            <li><a href="template/thumb4.jpg"
              data-gal="prettyPhoto[gallery]" title="Title"><%= image_tag 'template/thumb4.jpg', width: 150, height: 95 %></a></li>
          </ul>
        </article>

        <div class="clear"></div>
      </div>
      <div class="calloutoverlay"></div>
      <div class="calloutoverlaybottom"></div>
    </div>
  </div>
</div>
  <footer>
    <p class="tagline_left">
      Copyright &copy; 2011 - All Rights Reserved - <a href="#">rosario-ultimate.com.ar</a>
    </p>
    <p class="tagline_right">Design by <a href="http://www.priteshgupta.com/" title="Pritesh Gupta" target="_blank" >PriteshGupta.com</a></p>
    <br class="clear" />
  </footer>

  <br />
  <br />

</body>
</html>

app/views/layouts/articles.html.erb
<%= content_for :content do %>

<div class="container1">

<p class="error"><%= flash[:error] %></p>
<%= yield %>

</div>

<% end %>

<%= render template: 'layouts/application' %>

app/views/layouts/devise.html.erb
<%= content_for :content do %>
<div class="container1">
<div class="box">
<%= yield %>
</div>
</div>
<div class="container1">
<!-- TODO: Disable for Users -->
<% if can? :manage, User %>
<%= link_to 'Userpanel' , admin_userpanel_index_path %>
<% end %>
</div>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/home.html.erb
<% content_for :content do %>
<div class="container1">
  <div id="mySlides">
    <div id="slide1">
      <%= image_tag 'template/slider2.png' %> <span><b
        class="slideheading">First Featured Slide</b><br />Featured
        Text.....<a href="#" title="Coolness" class="readmore">Read
          More!</a></span>
    </div>
    <div id="slide2">
      <%= image_tag 'template/slider3.png' %> <span><b
        class="slideheading">Second Featured Slide</b><br />Featured
        Text.....<a href="#" title="Coolness" class="readmore">Read
          More!</a></span>
    </div>
    <div id="slide3">
      <%= image_tag 'template/slider1.png' %> <span><b
        class="slideheading">Third Featured Slide</b><br />Featured
        Text.....<a href="#" title="Coolness" class="readmore">Read
          More!</a></span>
    </div>
  </div>

  <div id="myController">
    <span class="jFlowControl"></span> <span class="jFlowControl"></span>
    <span class="jFlowControl"></span>
  </div>

  <section class="jFlowPrev">
    <div></div>
  </section>
  <section class="jFlowNext">
    <div></div>
  </section>
  <br /> <br />

  <article class="box" id="home_featured21">
    <% @articles.each do |article| %>
   
    <%= link_to article_path(article) do %>
    <div class="block">
        <div class="boxheader ellipsis"><h2><%= article.title %></h2></div>
        <div class="boxcontent ellipsis"><p><%= article.updated_at.to_s(:arg_time_format) %> <br><%= article.content.html_safe %></p></div> 
      </div>
    
    <% end %>
    <% end %>
    <div class="clear"></div>
    
    <div class="read_more"><%= link_to 'read more' , articles_path %></div> 
  </article>
 
</div>


  <% end %> <%= render template: 'layouts/application' %>

app/views/layouts/page.html.erb
<%= content_for :content do %>
<div class="container1">
	<div class="box">
		<%= yield %>
	</div>
</div>



<% if can? :manage, Page %>
<div class="container1">
<!-- TODO: Disable for Users -->
# <%= link_to 'edit', edit_page_path(@page) %> 
</div>

	<% end %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/page/_form.html.erb
<%= form_for @page do |f| %>	
<%= f.label 'name' %> <br>
<%= f.text_field 'name' %> <br>
<br>
<%= f.label 'header' %> <br>
<%= f.text_area 'header', size: '20x5' %> <br>
<br>
<%= f.label 'Content' %> <br>
<%= f.text_area 'content' %> <br>
<br>
<%= f.submit %>
<% end %>

app/views/page/about_us.html.erb
<% if @page %>
		<h1><%= @page.name %></h1>
		<p>
		<div>
			<div id="header1">
				<h2>
					<a href="index.html"><%= @page.header.html_safe %></a>
				</h2>
				<br>
				<p id="tagline1">
					<strong>Header Tagline</strong>
				</p>
				<br>
			</div>
		
		<div class="clear"></div>
		<%= @page.content.html_safe %>
		<br />

		<div class="clear"></div>
<% end %>
	</div>


</div>

app/views/page/edit.html.erb
<%= render 'form' %>

app/views/page/find_us.html.erb
<% if @page %>
		<h1><%= @page.name %></h1>
		<p>
		<div>
			<div id="header1">
				<h2>
					<a href="index.html"><%= @page.header.html_safe %></a>
				</h2>
				<br>
				<p id="tagline1">
					<strong>Header Tagline</strong>
				</p>
				<br>
			</div>
		
		<div class="clear"></div>
		<%= @page.content.html_safe %>
		<br />

		<div class="clear"></div>
<% end %>
	</div>


</div>

app/views/page/index.html.erb
<div class="container1">
<% @pages.each do |page| %>
	<%=  page.inspect %>
	<% end %>

app/views/page/show.html.erb
<%= @page.name %>
<%= @page.header %>
<%= @page.content %>

app/views/page/training.html.erb
Page#Training